version: '3.9'

services:
  # === Databases ===
  product-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    ports:
      - "5432:5432"

  order-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5433:5432"

  customer-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customers
    ports:
      - "5434:5432"

  # === Backend Services ===
  product-service:
    build: ./backend/product_service
    depends_on:
      - product-db
    environment:
      POSTGRES_HOST: product-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8001:80"

  order-service:
    build: ./backend/order_service
    depends_on:
      - order-db
    environment:
      POSTGRES_HOST: order-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8002:80"

  customer-service:
    build: ./backend/customer_service
    depends_on:
      - customer-db
    environment:
      POSTGRES_HOST: customer-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: customers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8003:80"

  # === Frontend ===
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - product-service
      - order-service
      - customer-service
