apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db
  labels:
    app: customer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
        - name: customer-db
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: customers
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db
  labels:
    app: customer-db
spec:
  selector:
    app: customer-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP